global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "market-sim"
    scrape_interval: 1s
    static_configs:
      - targets: ["localhost:9000"]
    metrics_path: "/prometheus/metrics"
    fallback_scrape_protocol: PrometheusText1.0.0
